EbookSystem/EbookSystem/Controllers/BrowseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EbookSystem.Models;

namespace EbookSystem.Controllers
{
    public class BrowseController : Controller
    {

        private SellDBContext db = new SellDBContext();
        //
        // GET: /Browse/

        public ActionResult Index()
        {
            return View(db.Sell.ToList());
        }
       
       public ActionResult SearchIndex(string searchString)
        {
            var books  = from m in db.Sell
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Title.Contains(searchString));
            }

            return View(books);
        }
     
        public ActionResult Details(int id = 0)
        {
            Sell sell = db.Sell.Find(id);
            if (sell == null)
            {
                return HttpNotFound();
            }
            return View(sell);
        }
        public ActionResult Order()
        {
            return View();
        }
        public ActionResult Comment()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Comment(Sell sell, int id = 0)
        {
            if (ModelState.IsValid)
            {
                Sell sell1 = db.Sell.Find(id);
                if (sell1 == null)
                {
                    return HttpNotFound();
                }

                db.Entry(sell1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sell);
        }
    }
}

EbookSystem/EbookSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EbookSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to our Ebook Sale System.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Ebook Sale System";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact us Page";

            return View();
        }
    }
}

EbookSystem/EbookSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    
</hgroup>

<article>
    <p>
        Electronic book sale system is a one-stop search engine that searches books for sale which could be new or used. The system helps you save time and money by searching every major catalog online, and letting you know which booksellers are offering the best prices and selection. When you find a book you like, you can buy it directly from the original seller. Electronic book sale system is an online marketplace for books. Thousand of new and used books are offered for sale through this system from thousands of booksellers around the world. Readers can find bestsellers, collectors can find rare books, students can find new and used textbooks, and treasure hunters can find long-lost books. The main goal of this system is to help people find and buy any book from any bookseller and our business stretches around the world. The unique inventory of books for sale from booksellers includes the world’s greatest books, countless out-of-print gems, millions of signed books, millions of used copies, a vast selection of college textbooks and new books too.
    </p>

    
</article>

<aside>
    <h3> Best Site For Buying and Selling Books

    </h3>

    <p>30 Million MEMBERS
        </p>
    <p>
        900 Million BOOKS ADDED
    </p>
    <p>
        400 Million COMMENTS
         </p>
    
</aside>

EbookSystem/EbookSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>718-225-0890</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>718-225-0080</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">ebooksystem@gmail.com</a></span>
    </p>
   
   
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        The City College of New York<br />
    160 Convent Ave, New York, NY 10031
    </p>
</section>

EbookSystem/EbookSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                @*<h1>@ViewBag.Title.</h1>*@
                <h1>@ViewBag.Message</h1>
            </hgroup>
           <p>
                Our Ebook System is a one-stop search engine that searches books for sale which could be new or used. The system helps you save time and money by 
searching every major catalog online, and letting you know which booksellers are offering the best prices and selection. When you find a book you like, you can 
buy it directly from this site. 
            </p>
        </div>
    </section>
}
<h2 style="color:steelblue;font-weight:bold;">Author Book Lists</h2>
<ol class="round">
    <li class="one">
        <h5>Best Books Ever</h5>
        Best books voted by our users.

        @Html.ActionLink("Learn more", "Index", "Browse")
        <br />
        <table>
            <tr>
               <td>
                    <img src="~/Images/book1.jpg" style="width:100px;"/></td>
                 <td>
                    <img src="~/Images/book2.jpg" style="width:100px;"/></td>
                 <td>
                    <img src="~/Images/book3.jpg" style="width:100px;"/></td>
                <td>
                    <img src="~/Images/book4.jpg" style="width:100px;"/></td>
            </tr>
           
        </table>
    </li>
    <li class="two">
        <h5>Best thriller books</h5>
        Best thriller books voted by our users.
         @Html.ActionLink("Learn more", "Index", "Browse")
    <br />
        <table>
            <tr>
               <td>
                    <img src="~/Images/thriller1.jpg" style="width:100px;"/></td>
                 <td>
                    <img src="~/Images/thriller2.jpg" style="width:100px;"/></td>
                 <td>
                    <img src="~/Images/thriller3.jpg" style="width:100px;"/></td>
               <td>
                    <img src="~/Images/thriller4.jpg" style="width:100px;"/></td>
            </tr>
             </table>
    
    </li>

    

</ol>